In [ ]:
# Import Pandas library
import pandas as pd

In [ ]:
# Import file upload/download tools from Google Colab
from google.colab import files

uploaded = files.upload()

Saving insurance_dataset.csv to insurance_dataset (1).csv

In [ ]:
# Read the CSV file into a DataFrame
df = pd.read_csv('insurance_dataset.csv')

In [ ]:
# Display the first 5 rows
df.head()

,Customer_ID,Age,Gender,Policy_Type,Premium,Claim_Count,Region,Date_Joined,Customer_Satisfaction
0,CUST0001,26,Female,Life,57.78,3,North,2019-09-20,1.0
1,CUST0002,22,M,Life,243.23,3,South,2021-11-21,10.0
2,CUST0003,28,NaN,Auto,341.58,2,North,2020-09-10,3.0
3,CUST0004,61,F,Life,235.81,1,West,2021-07-04,10.0
4,CUST0005,63,F,Auto,493.64,4,South,2019-01-20,3.0

In [ ]:
# Show the number of rows and columns
df.shape

(510, 9)

In [ ]:
# Show all column names
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'Policy_Type', 'Premium', 'Claim_Count',
       'Region', 'Date_Joined', 'Customer_Satisfaction'],
      dtype='object')

In [ ]:
# Show dataset information and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510 entries, 0 to 509
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            510 non-null    object
 1   Age                    510 non-null    int64
 2   Gender                 485 non-null    object
 3   Policy_Type            510 non-null    object
 4   Premium                484 non-null    float64
 5   Claim_Count            510 non-null    int64
 6   Region                 510 non-null    object
 7   Date_Joined            510 non-null    object
 8   Customer_Satisfaction  485 non-null    float64
dtypes: float64(2), int64(2), object(5)
memory usage: 36.0+ KB

In [ ]:
# Remove missing values
df.isnull().sum()

Customer_ID              0
Age                      0
Gender                   0
Policy_Type              0
Premium                  0
Claim_Count              0
Region                   0
Date_Joined              0
Customer_Satisfaction    0
dtype: int64

In [ ]:
# Remove rows containing missing values
df = df.dropna()

In [ ]:
# Check again
df.isnull().sum()

Customer_ID              0
Age                      0
Gender                   0
Policy_Type              0
Premium                  0
Claim_Count              0
Region                   0
Date_Joined              0
Customer_Satisfaction    0
dtype: int64

In [ ]:
# Show statistical summary of numerical columns
df.describe()

              Age     Premium  Claim_Count  Customer_Satisfaction
count  437.000000  437.000000   437.000000             437.000000
mean    47.917620  272.264920     1.974828               5.485126
std     17.555615  128.197994     1.398495               2.891443
min     18.000000   50.340000     0.000000               1.000000
25%     33.000000  158.510000     1.000000               3.000000
50%     47.000000  270.690000     2.000000               6.000000
75%     63.000000  380.550000     3.000000               8.000000
max     79.000000  497.560000     4.000000              10.000000

In [ ]:
# Check the number of duplicate rows
df.duplicated().sum()

np.int64(9)

In [ ]:
# Count the number of unique values in each column
df.nunique()

Customer_ID              428
Age                       62
Gender                     5
Policy_Type                3
Premium                  423
Claim_Count                5
Region                     4
Date_Joined              408
Customer_Satisfaction     10
dtype: int64